spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/XuKyle/spring-cloud-config
          search-paths: repo
      label: master

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/